from __future__ import annotations

from enum import StrEnum


class CaseStatus(StrEnum):
    NEW = "NEW"
    PROFILED = "PROFILED"
    DOCUMENTS_UPLOADED = "DOCUMENTS_UPLOADED"
    PROCESSING = "PROCESSING"
    COVERAGE_INCOMPLETE = "COVERAGE_INCOMPLETE"
    PORTAL_APPROVAL_REQUIRED = "PORTAL_APPROVAL_REQUIRED"
    BROWSER_ACTIVE = "BROWSER_ACTIVE"
    BROWSER_USER_ACTION_REQUIRED = "BROWSER_USER_ACTION_REQUIRED"
    DOCUMENT_RECOVERED = "DOCUMENT_RECOVERED"
    NEEDS_REVIEW = "NEEDS_REVIEW"
    READY_TO_CALCULATE = "READY_TO_CALCULATE"
    DRAFT_READY = "DRAFT_READY"
    APPROVED = "APPROVED"
    OUT_OF_SCOPE = "OUT_OF_SCOPE"
    FAILED = "FAILED"
    DELETED = "DELETED"


class JobStatus(StrEnum):
    ACCEPTED = "ACCEPTED"
    RUNNING = "RUNNING"
    WAITING_USER = "WAITING_USER"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"


class CoverageStatus(StrEnum):
    VERIFIED_WITH_CERTIFICATE = "VERIFIED_WITH_CERTIFICATE"
    VERIFIED_BY_USER = "VERIFIED_BY_USER"
    DUPLICATE = "DUPLICATE"
    NOT_APPLICABLE = "NOT_APPLICABLE"
    DOCUMENT_MISSING = "DOCUMENT_MISSING"
    CONFLICT = "CONFLICT"
    UNRESOLVED = "UNRESOLVED"


class MissingDocumentStatus(StrEnum):
    DISCOVERING = "DISCOVERING"
    AWAITING_PORTAL_APPROVAL = "AWAITING_PORTAL_APPROVAL"
    AWAITING_CONSENT = "AWAITING_CONSENT"
    BROWSING = "BROWSING"
    USER_ACTION_REQUIRED = "USER_ACTION_REQUIRED"
    DOWNLOADED = "DOWNLOADED"
    MANUAL_UPLOAD_REQUIRED = "MANUAL_UPLOAD_REQUIRED"
    FAILED = "FAILED"


class PortalCandidateSource(StrEnum):
    GATEWAY_WEB_SEARCH = "GATEWAY_WEB_SEARCH"
    SEEDED_DEMO = "SEEDED_DEMO"


class PortalCandidateStatus(StrEnum):
    UNVERIFIED = "UNVERIFIED"
    CANDIDATE = "CANDIDATE"
    USER_APPROVED = "USER_APPROVED"
    REJECTED = "REJECTED"


class EvidenceCandidateStatus(StrEnum):
    PROPOSED = "PROPOSED"
    CONFIRMED = "CONFIRMED"
    REJECTED = "REJECTED"


class ReconciliationIssueType(StrEnum):
    MISSING = "MISSING"
    CONFLICT = "CONFLICT"
    DUPLICATE = "DUPLICATE"
    UNSUPPORTED = "UNSUPPORTED"
    LOW_CONFIDENCE = "LOW_CONFIDENCE"


class DownloadStrategy(StrEnum):
    IN_PAGE_FETCH = "IN_PAGE_FETCH"
    COOKIE_GET = "COOKIE_GET"
    MOUNTED_FS = "MOUNTED_FS"


class AgentCommand(StrEnum):
    PREPARE_DRAFT = "PREPARE_DRAFT"
    FIND_MISSING_DOCUMENTS = "FIND_MISSING_DOCUMENTS"
    START_DOCUMENT_RECOVERY = "START_DOCUMENT_RECOVERY"
    RESUME_AFTER_USER_ACTION = "RESUME_AFTER_USER_ACTION"
    RESUME_AFTER_REVIEW = "RESUME_AFTER_REVIEW"
    EXPLAIN_CELL = "EXPLAIN_CELL"
    GENERATE_PACKET = "GENERATE_PACKET"
